# Generated by Django 3.2.5 on 2021-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='bookTitle')),
                ('ISBN', models.CharField(max_length=100, verbose_name='ISBN')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('count', models.IntegerField(verbose_name='count')),
                ('rentPrice', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='rentPrice')),
            ],
        ),
    ]
